version: "3.8"

services:

  pgdb:
    # Использование готового образа postgres
    image: postgres:16
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
    # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    networks:
      - network_undress
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
      timeout: 5s


  django-back:
    environment:
      - TZ=Europe/Moscow
    build:
      context: ./django-backend
      dockerfile: Dockerfile
    volumes:
      - ./django-backend/config:/usr/src/config
      - ./django-backend/config/static:/usr/src/config/static

    ports:
      - "8000:8000"
    depends_on:
      pgdb:
        condition: service_healthy
    restart: always
    networks:
      - network_undress



volumes:
  pgdbdata: null
  node_modules_data: null

networks:
  network_undress:
    driver: bridge
